package mx.qsistemas.infracciones.db.entities

import android.icu.text.SymbolTable

data class InfractionLocal(
        var REGISTRO_FECHA:String="",
        var FOLIO:String="",
        var BAN_INFRACTOR_AUSENTE:String="",
        var NOMBRE: String?="",
        var A_PATERNO:String?="",
        var A_MATERNO:String?="",
        var RFC:String?="",
        var EXTERIOR:String?="",
        var INTERIOR:String?="",
        var COL_PERSON:String?="",
        var CALLE_PERSON:String?="",
        var TARJETA_CIRCULACION: String?="",
        var TIPO: String?="",
        var EXPEDIDA_EN_LICENCIA:String?="",
        var MARCA_VEHICULO: String?="",
        var SUBMARCA:String?="",
        var COLOR: String?="",
        var MODELO: String?="",
        var DOCUMENTO: String?="",
        var AUTORIDAD: String?="",
        var DOCUMENTO_EXPEDIDO_EN: String?="",
        var CALLE_INFRA:String?="",
        var ENTRE_CALLE_INFRA: String?="",
        var Y_CALLE_INFRA:String?="",
        var COL_INFRA: String?="",
        var TOWN_INFRA:String?="",
        var DOCUMENTO_RETENIDO: String?="",
        var ID_DISPOSICION:Int=0,
        var DISPOSICION:String?="",
        var OFICIAL: String?="",
        var EMPLEADO: String?="",
        var FEC_LINEA_CAPTURA_II :String="",
        var LINEA_CAPTURA_II : String="",
        var IMPORTE_LINEA_CAPTURA_II : String="",
        var FEC_LINEA_CAPTURA_III : String="",
        var LINEA_CAPTURA_III : String="",
        var IMPORTE_LINEA_CAPTURA_III: String="",
        var ESTADO_INFRACTOR:String?="",
        var ESTADO_INFRACCION:String?="",
        var NUM_DOCUMENTO_IDENTIFICADOR: String=""
)