package mx.qsistemas.infracciones.DataManagement;

import android.os.Environment;

/**
 * Developed by ingmtz on 10/17/16.
 */

public class Const {
    static final String PREF_NAME = "INFRAPREF";
    public static final String SD_PATH_IMG = Environment.getExternalStorageDirectory().getPath() + "/.qsistemas/INFRACCIONES/FOTOS/";
    public static final String DATABASE_NAME = Environment.getExternalStorageDirectory().getPath() + "/.qsistemas/INFRACCIONES/DB/INFRACCIONES.db";
    public static final Integer OXXO_LENGTH = 32;
    public static final Integer OXXO_FECHA_LENGTH = 8;
    public static final Integer OXXO_IMPORTE_LENGTH = 7;
    public static final Integer OXXO_VERIFICADOR_LENGTH = 1;
    public static final String OXXO_IDENTIFICADOR = "17";

    public class Database {

        public static final int DATABASE_VERSION = 2;
        public class Tables {
            public static final String TABLE_MARCA = "SIIPTC_MARCA_VEHICULO";
            public static final String TABLE_SUBMARCA = "SIIPTC_SUBMARCA_VEHICULO";
            public static final String TABLE_TIPOVEHICULO = "SIIPTC_INFRACCION_TIPO_VEHICULO";
            public static final String TABLE_COLOR = "SIIPTC_COLOR";
            public static final String TABLE_DOCIDENT = "SIIPTC_INFRACCION_DOCUMENTO_IDENTIFICADOR";
            public static final String TABLE_ESTADO = "SIIPTC_ESTADO";
            public static final String TABLE_AUTEXPIDE = "SIIPTC_INFRACCION_AUTORIDAD_EXPIDE";
            public static final String TABLE_ARTICULO = "SIIPTC_INFRACCION_ARTICULO";
            public static final String TABLE_FRACCION = "SIIPTC_INFRACCION_FRACCION";
            public static final String TABLE_DISPOSICION = "SIIPTC_INFRACCION_DISPOSICION";
            public static final String TABLE_DOCRETENIDO = "SIIPTC_INFRACCION_DOCUMENTO_RETENIDO";
            public static final String TABLE_MUNICIPIO = "SIIPTC_MUNICIPIO_SEPOMEX";
            public static final String TABLE_TIPOLIC = "SIIPTC_INFRACCION_TIPO_LICENCIA";
            public static final String TABLE_CONFIG = "SIIPTC_CONFIGURACION";
            public static final String TABLE_INFRACCION = "SIIPTA_INFRACCION";
            public static final String TABLE_DIANOHABIL = "SIIPTC_DIA_NO_HABIL";
            public static final String TABLE_ATRIBS = "SIIPTA_PERSONA_ATRIBUTO";
        }

        public class SQLQueries {

            public class Catalogs{
                public static final String GET_LAST_INFRA = "SELECT FOLIO FROM SIIPTA_INFRACCION WHERE FOLIO LIKE '";
            }

            public class Create {
                public static final String CREATE_SIIPTC_CONFIGURACION = "CREATE TABLE SIIPTC_CONFIGURACION (SALARIO_MINIMO REAL, PLAZO_DIAS_DESCUENTO_INFRACCION INTEGER, TAZA_DESCUENTO_INFRACCION_MISMO_DIA REAL);";
                public static final String CREATE_SIIPTC_DIA_NO_HABIL = "CREATE TABLE SIIPTC_DIA_NO_HABIL (ID_DIA INTEGER PRIMARY KEY, FECHA TEXT);";
                public static final String CREATE_SIIPTC_FOLIO = "CREATE TABLE SIIPTC_FOLIO (INFRACCION INTEGER, REFERENCIA_BANCO INTEGER);";
                public static final String CREATE_SIIPTC_KEY = "CREATE TABLE SIIPTC_KEY (DECRYPT TEXT);";
                public static final String CREATE_SIIPTC_SINCRONIZACION = "CREATE TABLE SIIPTC_SINCRONIZACION (INFRACCION_CATALOGOS INTEGER, APLICACION_ACTIVA INTEGER, PAUSA_GUARDAR INTEGER, ULTIMA_SINCRONIZACION_CATALOGOS TEXT);";
                public static final String CREATE_SIIPTC_INFRACCION_AUTORIDAD_EXPIDE = "CREATE TABLE SIIPTC_INFRACCION_AUTORIDAD_EXPIDE (ID_AUTORIDAD_EXPIDE INTEGER PRIMARY KEY, AUTORIDAD TEXT);";
                public static final String CREATE_SIIPTC_INFRACCION_DISPOSICION = "CREATE TABLE SIIPTC_INFRACCION_DISPOSICION (ID_DISPOSICION INTEGER PRIMARY KEY, DISPOSICION TEXT);";
                public static final String CREATE_SIIPTC_INFRACCION_DOCUMENTO_RETENIDO = "CREATE TABLE SIIPTC_INFRACCION_DOCUMENTO_RETENIDO (ID_DOCUMENTO_RETENIDO INTEGER PRIMARY KEY, DOCUMENTO TEXT);";
                public static final String CREATE_SIIPTC_INFRACCION_TIPO_LICENCIA = "CREATE TABLE SIIPTC_INFRACCION_TIPO_LICENCIA (ID_TIPO_LICENCIA INTEGER PRIMARY KEY, TIPO_LICENCIA TEXT);";
                public static final String CREATE_SIIPTC_PERSONA = "CREATE TABLE SIIPTC_PERSONA (ID_PERSONA INTEGER PRIMARY KEY, NOMBRE TEXT, A_PATERNO TEXT, A_MATERNO TEXT, RFC TEXT);";
                public static final String CREATE_SIIPTC_PERSONA_AYUNTAMIENTO = "CREATE TABLE SIIPTC_PERSONA_AYUNTAMIENTO (ID_PERSONA_AYUNTAMIENTO INTEGER PRIMARY KEY, ID_PERSONA INTEGER, EMPLEADO TEXT, FOREIGN KEY (ID_PERSONA) REFERENCES SIIPTC_PERSONA(ID_PERSONA));";
                public static final String CREATE_SIIPTA_PERSONA_CUENTA = "CREATE TABLE SIIPTA_PERSONA_CUENTA (ID_CUENTA_USUARIO INTEGER PRIMARY KEY, ID_PERSONA INTEGER, BAN_ACTIVA INTEGER, USER_NAME TEXT, PASSWORD TEXT, FOREIGN KEY (ID_PERSONA) REFERENCES SIIPTC_PERSONA(ID_PERSONA));";
                public static final String CREATE_SIIPTC_MODULO = "CREATE TABLE SIIPTC_MODULO (ID_MODULO INTEGER PRIMARY KEY, MODULO TEXT);";
                public static final String CREATE_SIIPTC_ATRIBUTO = "CREATE TABLE SIIPTC_ATRIBUTO (ID_ATRIBUTO INTEGER PRIMARY KEY, ID_MODULO INTEGER, ATRIBUTO TEXT, FOREIGN KEY (ID_MODULO) REFERENCES SIIPTC_MODULO(ID_MODULO));";
                public static final String CREATE_SIIPTA_PERSONA_ATRIBUTO = "CREATE TABLE SIIPTA_PERSONA_ATRIBUTO (ID_PERSONA_ATRIBUTO INTEGER, ID_PERSONA INTEGER, ID_ATRIBUTO INTEGER, FOREIGN KEY (ID_PERSONA) REFERENCES SIIPTC_PERSONA(ID_PERSONA), FOREIGN KEY (ID_ATRIBUTO) REFERENCES SIIPTC_ATRIBUTO(ID_ATRIBUTO));";
                public static final String CREATE_SIIPTC_INFRACCION_ARTICULO = "CREATE TABLE SIIPTC_INFRACCION_ARTICULO (ID_ARTICULO INTEGER PRIMARY KEY, ARTICULO TEXT, DESCRIPCION TEXT);";
                public static final String CREATE_SIIPTC_INFRACCION_FRACCION = "CREATE TABLE SIIPTC_INFRACCION_FRACCION (ID_FRACCION INTEGER PRIMARY KEY, ID_ARTICULO INTEGER, FRACCION TEXT, DESCRIPCION TEXT, ALIAS_TICKET TEXT, SALARIOS_MINIMOS INTEGER, PUNTOS_SANCION INTEGER, FOREIGN KEY (ID_ARTICULO) REFERENCES SIIPTC_INFRACCION_ARTICULO(ID_ARTICULO));";
                public static final String CREATE_SIIPTC_PAIS = "CREATE TABLE SIIPTC_PAIS (ID_PAIS INTEGER PRIMARY KEY, PAIS TEXT);";
                public static final String CREATE_SIIPTC_ESTADO = "CREATE TABLE SIIPTC_ESTADO (ID_ESTADO INTEGER PRIMARY KEY, ID_PAIS INTEGER, ESTADO TEXT);";
                public static final String CREATE_SIIPTC_MUNICIPIO_SEPOMEX = "CREATE TABLE SIIPTC_MUNICIPIO_SEPOMEX (ID_MUNICIPIO INTEGER PRIMARY KEY, ID_ESTADO INTEGER, MUNICIPIO TEXT, FOREIGN KEY (ID_ESTADO) REFERENCES SIIPTC_ESTADO(ID_ESTADO));";
                public static final String CREATE_SIIPTA_DIRECCION = "CREATE TABLE SIIPTA_DIRECCION (ID_DIRECCION INTEGER PRIMARY KEY, ID_PAIS INTEGER, ID_ESTADO INTEGER, COLONIA TEXT, CALLE TEXT, EXTERIOR TEXT, INTERIOR TEXT, ENTRE_CALLE TEXT, Y_CALLE TEXT, ID_MUNICIPIO INTEGER, X REAL, Y REAL, FOREIGN KEY (ID_MUNICIPIO) REFERENCES SIIPTC_MUNICIPIO_SEPOMEX(ID_MUNICIPIO), FOREIGN KEY (ID_PAIS) REFERENCES SIIPTC_PAIS(ID_PAIS), FOREIGN KEY (ID_ESTADO) REFERENCES SIIPTC_ESTADO(ID_ESTADO));";
                public static final String CREATE_SIIPTA_DIRECCION_PERSONA_INFRACTOR = "CREATE TABLE SIIPTA_DIRECCION_PERSONA_INFRACTOR (ID_DIRECCION INTEGER, ID_PERSONA INTEGER, FOREIGN KEY (ID_DIRECCION) REFERENCES SIIPTA_DIRECCION(ID_DIRECCION), FOREIGN KEY (ID_PERSONA) REFERENCES SIIPTC_PERSONA(ID_PERSONA));";
                public static final String CREATE_SIIPTC_COLOR = "CREATE TABLE SIIPTC_COLOR (ID_COLOR INTEGER PRIMARY KEY, COLOR TEXT);";
                public static final String CREATE_SIIPTC_INFRACCION_TIPO_VEHICULO = "CREATE TABLE SIIPTC_INFRACCION_TIPO_VEHICULO (ID_TIPO INTEGER PRIMARY KEY, TIPO TEXT);";
                public static final String CREATE_SIIPTC_INFRACCION_DOCUMENTO_IDENTIFICADOR = "CREATE TABLE SIIPTC_INFRACCION_DOCUMENTO_IDENTIFICADOR (ID_DOCUMENTO_IDENTIFICADOR INTEGER PRIMARY KEY, DOCUMENTO TEXT);";
                public static final String CREATE_SIIPTC_MARCA_VEHICULO = "CREATE TABLE SIIPTC_MARCA_VEHICULO (ID_MARCA_VEHICULO INTEGER PRIMARY KEY, MARCA_VEHICULO TEXT);";
                public static final String CREATE_SIIPTC_SUBMARCA_VEHICULO = "CREATE TABLE SIIPTC_SUBMARCA_VEHICULO (ID_SUBMARCA_VEHICULO INTEGER PRIMARY KEY, ID_MARCA_VEHICULO INTEGER, SUBMARCA_VEHICULO TEXT, FOREIGN KEY (ID_MARCA_VEHICULO) REFERENCES SIIPTC_MARCA_VEHICULO(ID_MARCA_VEHICULO));";
                public static final String CREATE_SIIPTA_INFRACCION_VEHICULO = "CREATE TABLE SIIPTA_INFRACCION_VEHICULO (ID_VEHICULO INTEGER PRIMARY KEY, ID_SUBMARCA_VEHICULO INTEGER, ID_TIPO INTEGER, ID_COLOR INTEGER, MODELO TEXT, ID_DOCUMENTO_IDENTIFICADOR INTEGER, NUM_DOCUMENTO_IDENTIFICADOR TEXT, DOCUMENTO_EXPEDIDO_EN INTEGER, TARJETA_CIRCULACION TEXT, FOREIGN KEY (ID_SUBMARCA_VEHICULO) REFERENCES SIIPTC_SUBMARCA_VEHICULO(ID_SUBMARCA_VEHICULO), FOREIGN KEY (ID_TIPO) REFERENCES SIIPTC_INFRACCION_TIPO_VEHICULO(ID_TIPO), FOREIGN KEY (ID_COLOR) REFERENCES SIIPTC_COLOR(ID_COLOR), FOREIGN KEY (ID_DOCUMENTO_IDENTIFICADOR) REFERENCES SIIPTC_INFRACCION_DOCUMENTO_IDENTIFICADOR(ID_DOCUMENTO_IDENTIFICADOR), FOREIGN KEY (DOCUMENTO_EXPEDIDO_EN) REFERENCES SIIPTC_ESTADO(ID_ESTADO));";
                public static final String CREATE_SIIPTA_INFRACCION = "CREATE TABLE SIIPTA_INFRACCION (ID_INFRACCION INTEGER PRIMARY KEY, FOLIO TEXT, NUM_PERMISO_LICENCIA TEXT, ID_TIPO_LICENCIA INTEGER, EXPEDIDA_EN_LICENCIA TEXT, MOTIVO TEXT, BAN_REMITIDO_DEPOSITO INTEGER, SALARIOS_MIN INTEGER, IMPORTE REAL, TAZA_SALARIO_MIN REAL, BAN_PAGADA INTEGER, ID_INFRACCION_FUENTE INTEGER, ID_SECTOR INTEGER, ID_PERSONA_AYUNTAMIENTO INTEGER, ID_STATUS INTEGER, NUM_HOJAS_EXPEDIENTE INTEGER, FECHA_HORA TEXT, ID_DOCUMENTO_RETENIDO TEXT, ID_AUTORIDAD_EXPIDE INTEGER, FOLIO_EVIDENCIA TEXT, ID_DISPOSICION INTEGER, BAN_INFRACTOR_AUSENTE INTEGER, PUNTOS_SANCION INTEGER, BAN_ACTUALIZA INTEGER, LINEA_CAPTURA_I TEXT, LINEA_CAPTURA_II TEXT, LINEA_CAPTURA_III TEXT, FEC_LINEA_CAPTURA_I TEXT, FEC_LINEA_CAPTURA_II TEXT, FEC_LINEA_CAPTURA_III TEXT, IMPORTE_LINEA_CAPTURA_I REAL, IMPORTE_LINEA_CAPTURA_II REAL, IMPORTE_LINEA_CAPTURA_III REAL, IS_SYNC INTEGER, FOREIGN KEY (ID_PERSONA_AYUNTAMIENTO) REFERENCES SIIPTC_PERSONA_AYUNTAMIENTO(ID_PERSONA_AYUNTAMIENTO) , FOREIGN KEY (ID_AUTORIDAD_EXPIDE) REFERENCES SIIPTC_INFRACCION_AUTORIDAD_EXPIDE(ID_AUTORIDAD_EXPIDE) , FOREIGN KEY (ID_DISPOSICION) REFERENCES SIIPTC_INFRACCION_DISPOSICION(ID_DISPOSICION) , FOREIGN KEY (ID_DOCUMENTO_RETENIDO) REFERENCES SIIPTC_INFRACCION_DOCUMENTO_RETENIDO(ID_DOCUMENTO_RETENIDO) , FOREIGN KEY (ID_TIPO_LICENCIA) REFERENCES SIIPTC_INFRACCION_TIPO_LICENCIA(ID_TIPO_LICENCIA), FOREIGN KEY (EXPEDIDA_EN_LICENCIA) REFERENCES SIIPTC_ESTADO(ID_ESTADO));";
                public static final String CREATE_SIIPTA_INFRACCION_PAGO = "CREATE TABLE SIIPTA_INFRACCION_PAGO (ID_INFRACCION_PAGO INTEGER PRIMARY KEY, ID_INFRACCION INTEGER, ID_FORMA_PAGO INTEGER, SUBTOTAL REAL, DESCUENTO REAL, TOTAL REAL, FOLIO TEXT, OBSERVACION TEXT, ID_REGISTRO_USUARIO INTEGER, REGISTRO_FECHA TEXT, RECARGOS REAL, FOREIGN KEY (ID_INFRACCION) REFERENCES SIIPTA_INFRACCION(ID_INFRACCION), FOREIGN KEY (ID_REGISTRO_USUARIO) REFERENCES SIIPTC_CONFIGURACION(ID_REGISTRO_USUARIO));";
                public static final String CREATE_SIIPTA_INFRACCION_PAGO_TARJETA = "CREATE TABLE SIIPTA_INFRACCION_PAGO_TARJETA (ID_INFRACCION_PAGO_TARJETA INTEGER PRIMARY KEY, ID_INFRACCION INTEGER, AID TEXT, APP_LABEL TEXT, ARQC TEXT, AUTH_NB TEXT, ENTRY_TYPE TEXT, MASKED_PAN TEXT, TRX_DATE TEXT, TRX_NB TEXT, TRX_TIME TEXT, SERIAL_PAYPDA TEXT, ID_REGISTRO_USUARIO INTEGER, REGISTRO_FECHA TEXT, AFILIACION TEXT, VIGENCIA_TARJETA TEXT, MENSAJE TEXT, TIPO_TARJETA TEXT, TIPO TEXT, BANCO_EMISOR TEXT, REFERENCIA TEXT, IMPORTE TEXT, TVR TEXT, TSI TEXT, NUMERO_CONTROL TEXT, TARJETAHABIENTE TEXT, EMV_DATA TEXT, TIPO_TRANSACCION TEXT, FOREIGN KEY (ID_INFRACCION) REFERENCES SIIPTA_INFRACCION(ID_INFRACCION), FOREIGN KEY (ID_REGISTRO_USUARIO) REFERENCES SIIPTC_CONFIGURACION(ID_REGISTRO_USUARIO));";
                public static final String CREATE_SIIPTA_INFRACCION_FRACCION = "CREATE TABLE SIIPTA_INFRACCION_FRACCION (ID_INFRACCION INTEGER, ID_FRACCION INTEGER, FOREIGN KEY (ID_INFRACCION) REFERENCES SIIPTA_INFRACCION(ID_INFRACCION), FOREIGN KEY (ID_FRACCION) REFERENCES SIIPTC_INFRACCION_FRACCION(ID_FRACCION));";
                public static final String CREATE_SIIPTA_INFRACCION_INFRACCION_VEHICULO = "CREATE TABLE SIIPTA_INFRACCION_INFRACCION_VEHICULO (ID_INFRACCION INTEGER, ID_VEHICULO INTEGER, FOREIGN KEY (ID_INFRACCION) REFERENCES SIIPTA_INFRACCION(ID_INFRACCION), FOREIGN KEY (ID_VEHICULO) REFERENCES SIIPTA_INFRACCION_VEHICULO(ID_VEHICULO));";
                public static final String CREATE_SIIPTA_INFRACCION_PERSONA_INFRACTOR = "CREATE TABLE SIIPTA_INFRACCION_PERSONA_INFRACTOR (ID_INFRACCION INTEGER, ID_PERSONA INTEGER, FOREIGN KEY (ID_INFRACCION) REFERENCES SIIPTA_INFRACCION(ID_INFRACCION), FOREIGN KEY (ID_PERSONA) REFERENCES SIIPTC_PERSONA(ID_PERSONA));";
                public static final String CREATE_SIIPTA_DIRECCION_INFRACCION = "CREATE TABLE SIIPTA_DIRECCION_INFRACCION (ID_DIRECCION INTEGER, ID_INFRACCION INTEGER, FOREIGN KEY (ID_DIRECCION) REFERENCES SIIPTA_DIRECCION(ID_DIRECCION),FOREIGN KEY (ID_INFRACCION) REFERENCES SIIPTA_INFRACCION(ID_INFRACCION));";
                public static final String CREATE_SIIPTC_ADSCRIPCION = "CREATE TABLE SIIPTC_ADSCRIPCION (ID_ADSCRIPCION INTEGER, ADSCRIPCION TEXT, BAN_VISIBLE TEXT);";
                public static final String ADD_SINC = "INSERT INTO SIIPTC_SINCRONIZACION (ULTIMA_SINCRONIZACION_CATALOGOS) VALUES ('01/01/2000 00:00');";
                public static final String CREATE_IMAGESYNC = "CREATE TABLE IMAGE_SYNC (ID_IMG INTEGER PRIMARY KEY, NAME TEXT);";
            }

            //public static final String GET_USER_LOGIN = "SELECT SIIPTC_PERSONA_AYUNTAMIENTO.ID_PERSONA_AYUNTAMIENTO, SIIPTA_PERSONA_CUENTA.USER_NAME, SIIPTA_PERSONA_CUENTA.PASSWORD, SIIPTC_PERSONA.NOMBRE, SIIPTC_PERSONA.A_PATERNO, SIIPTC_PERSONA.A_MATERNO FROM SIIPTC_PERSONA INNER JOIN SIIPTA_PERSONA_CUENTA ON SIIPTC_PERSONA.ID_PERSONA = SIIPTA_PERSONA_CUENTA.ID_PERSONA INNER JOIN SIIPTC_PERSONA_AYUNTAMIENTO ON SIIPTC_PERSONA.ID_PERSONA = SIIPTC_PERSONA_AYUNTAMIENTO.ID_PERSONA WHERE USER_NAME = '";
            public static final String GET_USER_LOGIN = "SELECT SIIPTC_PERSONA_AYUNTAMIENTO.ID_PERSONA_AYUNTAMIENTO, SIIPTA_PERSONA_CUENTA.USER_NAME, SIIPTA_PERSONA_CUENTA.PASSWORD, SIIPTC_PERSONA.NOMBRE, SIIPTC_PERSONA.A_PATERNO, SIIPTC_PERSONA.A_MATERNO, SIIPTC_PERSONA.ID_PERSONA FROM SIIPTC_PERSONA INNER JOIN SIIPTA_PERSONA_CUENTA ON SIIPTC_PERSONA.ID_PERSONA = SIIPTA_PERSONA_CUENTA.ID_PERSONA INNER JOIN SIIPTC_PERSONA_AYUNTAMIENTO ON SIIPTC_PERSONA.ID_PERSONA = SIIPTC_PERSONA_AYUNTAMIENTO.ID_PERSONA WHERE USER_NAME = '";
            public static final String GET_ATRIBUTOS = "SELECT SIIPTA_PERSONA_ATRIBUTO.ID_ATRIBUTO FROM SIIPTA_PERSONA_ATRIBUTO WHERE ID_PERSONA ='";

            public class Insert {
                public static final String INSERT_ADMIN_SIIPTC_MODULO = "INSERT INTO SIIPTC_MODULO VALUES ('0', 'ADMINISTRADOR');";
                public static final String INSERT_ADMIN_SIIPTC_ATRIBUTO = "INSERT INTO SIIPTC_ATRIBUTO VALUES ('0', '0', 'SUPERUSER');";
                public static final String INSERT_ADMIN_SIIPTC_PERSONA = "INSERT INTO SIIPTC_PERSONA VALUES ('0', 'ADMINISTRADOR', 'QUETZALCOATL', 'SISTEMAS', 'QSIS000000');";
                public static final String INSERT_ADMIN_SIIPTC_PERSONA_AYUNTAMIENTO = "INSERT INTO SIIPTC_PERSONA_AYUNTAMIENTO VALUES ('000000', '0', '0');";
                public static final String INSERT_ADMIN_SIIPTA_PERSONA_CUENTA = "INSERT INTO SIIPTA_PERSONA_CUENTA VALUES ('0', '0', '1', 'MOBILE', 'D9E3110063BA107AB79340DCEEBC2D7B');";
                public static final String INSERT_ADMIN_SIIPTA_PERSONA_ATRIBUTO = "INSERT INTO SIIPTA_PERSONA_ATRIBUTO VALUES ('0', '0', '0');";
                public static final String INSERT_PERSONA = "INSERT INTO SIIPTC_PERSONA (NOMBRE, A_PATERNO, A_MATERNO, RFC) VALUES ('";


                public class Save {
                    public static final String INSERT_INFRA_1 = "INSERT INTO SIIPTA_INFRACCION (FOLIO, NUM_PERMISO_LICENCIA, ID_TIPO_LICENCIA, EXPEDIDA_EN_LICENCIA, MOTIVO, BAN_REMITIDO_DEPOSITO, SALARIOS_MIN, IMPORTE, TAZA_SALARIO_MIN, BAN_PAGADA, ID_PERSONA_AYUNTAMIENTO, FECHA_HORA, ID_DOCUMENTO_RETENIDO, ID_AUTORIDAD_EXPIDE, ID_DISPOSICION, BAN_INFRACTOR_AUSENTE, PUNTOS_SANCION, LINEA_CAPTURA_I, LINEA_CAPTURA_II, LINEA_CAPTURA_III, FEC_LINEA_CAPTURA_I, FEC_LINEA_CAPTURA_II, FEC_LINEA_CAPTURA_III, IMPORTE_LINEA_CAPTURA_I, IMPORTE_LINEA_CAPTURA_II, IMPORTE_LINEA_CAPTURA_III, IS_SYNC) VALUES(";
                    public static final String INSERT_INFRA_2 = "INSERT INTO SIIPTA_INFRACCION (FOLIO, NUM_PERMISO_LICENCIA, ID_TIPO_LICENCIA, EXPEDIDA_EN_LICENCIA, MOTIVO, BAN_REMITIDO_DEPOSITO, SALARIOS_MIN, IMPORTE, TAZA_SALARIO_MIN, BAN_PAGADA, ID_PERSONA_AYUNTAMIENTO, FECHA_HORA, ID_DOCUMENTO_RETENIDO, ID_AUTORIDAD_EXPIDE, ID_DISPOSICION, BAN_INFRACTOR_AUSENTE, PUNTOS_SANCION, LINEA_CAPTURA_I, LINEA_CAPTURA_II, LINEA_CAPTURA_III, FEC_LINEA_CAPTURA_I, FEC_LINEA_CAPTURA_II, FEC_LINEA_CAPTURA_III, IMPORTE_LINEA_CAPTURA_I, IMPORTE_LINEA_CAPTURA_II, IMPORTE_LINEA_CAPTURA_III, BAN_ACTUALIZA, IS_SYNC) VALUES(";
                }


            }

            public class Search {
                public static final String SEARCH_INFRA = "SELECT SIIPTA_INFRACCION.ID_INFRACCION, SIIPTA_INFRACCION.FOLIO, SIIPTA_DIRECCION.CALLE, SIIPTA_DIRECCION.ENTRE_CALLE, SIIPTA_DIRECCION.Y_CALLE, SIIPTA_DIRECCION.COLONIA, SIIPTA_INFRACCION_VEHICULO.MODELO, SIIPTA_INFRACCION_VEHICULO.NUM_DOCUMENTO_IDENTIFICADOR, SIIPTA_INFRACCION_VEHICULO.TARJETA_CIRCULACION, SIIPTA_INFRACCION.MOTIVO, SIIPTA_INFRACCION.SALARIOS_MIN, SIIPTA_INFRACCION.IMPORTE, SIIPTA_INFRACCION.PUNTOS_SANCION, SIIPTA_INFRACCION.LINEA_CAPTURA_I, SIIPTA_INFRACCION.LINEA_CAPTURA_II, SIIPTA_INFRACCION.LINEA_CAPTURA_III, SIIPTA_INFRACCION.FEC_LINEA_CAPTURA_I, SIIPTA_INFRACCION.FEC_LINEA_CAPTURA_II, SIIPTA_INFRACCION.FEC_LINEA_CAPTURA_III, SIIPTA_INFRACCION.IMPORTE_LINEA_CAPTURA_I, SIIPTA_INFRACCION.IMPORTE_LINEA_CAPTURA_II, SIIPTA_INFRACCION.IMPORTE_LINEA_CAPTURA_III, SIIPTA_INFRACCION.ID_PERSONA_AYUNTAMIENTO, SIIPTA_INFRACCION.FECHA_HORA, SIIPTC_SUBMARCA_VEHICULO.ID_MARCA_VEHICULO, SIIPTC_MARCA_VEHICULO.MARCA_VEHICULO, SIIPTA_INFRACCION_VEHICULO.ID_SUBMARCA_VEHICULO, SIIPTC_SUBMARCA_VEHICULO.SUBMARCA_VEHICULO, SIIPTA_INFRACCION_VEHICULO.ID_TIPO, SIIPTC_INFRACCION_TIPO_VEHICULO.TIPO, SIIPTA_INFRACCION_VEHICULO.ID_COLOR, SIIPTC_COLOR.COLOR, SIIPTA_INFRACCION_VEHICULO.ID_DOCUMENTO_IDENTIFICADOR, SIIPTC_INFRACCION_DOCUMENTO_IDENTIFICADOR.DOCUMENTO, SIIPTA_INFRACCION.ID_AUTORIDAD_EXPIDE, SIIPTC_INFRACCION_AUTORIDAD_EXPIDE.AUTORIDAD, SIIPTA_INFRACCION_VEHICULO.DOCUMENTO_EXPEDIDO_EN, SIIPTC_ESTADO.ESTADO, SIIPTA_INFRACCION.TAZA_SALARIO_MIN, SIIPTA_INFRACCION.BAN_REMITIDO_DEPOSITO, SIIPTA_INFRACCION.BAN_INFRACTOR_AUSENTE, SIIPTA_INFRACCION_INFRACCION_VEHICULO.ID_VEHICULO, SIIPTC_INFRACCION_DOCUMENTO_RETENIDO.ID_DOCUMENTO_RETENIDO, SIIPTC_INFRACCION_DOCUMENTO_RETENIDO.DOCUMENTO, SIIPTA_INFRACCION.IS_SYNC, SIIPTA_INFRACCION.BAN_ACTUALIZA , SIIPTA_DIRECCION.X , SIIPTA_DIRECCION.Y FROM SIIPTA_INFRACCION LEFT JOIN SIIPTA_DIRECCION_INFRACCION ON SIIPTA_INFRACCION.ID_INFRACCION = SIIPTA_DIRECCION_INFRACCION.ID_INFRACCION LEFT JOIN SIIPTA_DIRECCION ON SIIPTA_DIRECCION_INFRACCION.ID_DIRECCION = SIIPTA_DIRECCION.ID_DIRECCION LEFT JOIN SIIPTA_INFRACCION_INFRACCION_VEHICULO ON SIIPTA_INFRACCION.ID_INFRACCION = SIIPTA_INFRACCION_INFRACCION_VEHICULO.ID_INFRACCION LEFT JOIN SIIPTC_INFRACCION_AUTORIDAD_EXPIDE ON SIIPTA_INFRACCION.ID_AUTORIDAD_EXPIDE = SIIPTC_INFRACCION_AUTORIDAD_EXPIDE.ID_AUTORIDAD_EXPIDE LEFT JOIN SIIPTA_INFRACCION_VEHICULO ON SIIPTA_INFRACCION_INFRACCION_VEHICULO.ID_VEHICULO = SIIPTA_INFRACCION_VEHICULO.ID_VEHICULO LEFT JOIN SIIPTC_ESTADO ON SIIPTA_INFRACCION_VEHICULO.DOCUMENTO_EXPEDIDO_EN = SIIPTC_ESTADO.ID_ESTADO LEFT JOIN SIIPTC_SUBMARCA_VEHICULO ON SIIPTA_INFRACCION_VEHICULO.ID_SUBMARCA_VEHICULO = SIIPTC_SUBMARCA_VEHICULO.ID_SUBMARCA_VEHICULO LEFT JOIN SIIPTC_INFRACCION_TIPO_VEHICULO ON SIIPTA_INFRACCION_VEHICULO.ID_TIPO = SIIPTC_INFRACCION_TIPO_VEHICULO.ID_TIPO LEFT JOIN SIIPTC_COLOR ON SIIPTA_INFRACCION_VEHICULO.ID_COLOR = SIIPTC_COLOR.ID_COLOR LEFT JOIN SIIPTC_INFRACCION_DOCUMENTO_IDENTIFICADOR ON SIIPTA_INFRACCION_VEHICULO.ID_DOCUMENTO_IDENTIFICADOR = SIIPTC_INFRACCION_DOCUMENTO_IDENTIFICADOR.ID_DOCUMENTO_IDENTIFICADOR LEFT JOIN SIIPTC_MARCA_VEHICULO ON SIIPTC_SUBMARCA_VEHICULO.ID_MARCA_VEHICULO = SIIPTC_MARCA_VEHICULO.ID_MARCA_VEHICULO LEFT JOIN SIIPTC_INFRACCION_DOCUMENTO_RETENIDO ON SIIPTA_INFRACCION.ID_DOCUMENTO_RETENIDO = SIIPTC_INFRACCION_DOCUMENTO_RETENIDO.ID_DOCUMENTO_RETENIDO ";
                public static final String SEARCH_FRACCION = "SELECT SIIPTC_INFRACCION_ARTICULO.ARTICULO, SIIPTC_INFRACCION_FRACCION.FRACCION, SIIPTC_INFRACCION_FRACCION.DESCRIPCION, SIIPTC_INFRACCION_FRACCION.SALARIOS_MINIMOS, SIIPTC_INFRACCION_FRACCION.PUNTOS_SANCION, SIIPTC_INFRACCION_FRACCION.ID_FRACCION, SIIPTC_INFRACCION_FRACCION.ID_ARTICULO FROM SIIPTC_INFRACCION_ARTICULO LEFT JOIN SIIPTC_INFRACCION_FRACCION ON SIIPTC_INFRACCION_ARTICULO.ID_ARTICULO = SIIPTC_INFRACCION_FRACCION.ID_ARTICULO LEFT JOIN SIIPTA_INFRACCION_FRACCION ON SIIPTC_INFRACCION_FRACCION.ID_FRACCION = SIIPTA_INFRACCION_FRACCION.ID_FRACCION WHERE SIIPTA_INFRACCION_FRACCION.ID_INFRACCION = '";
                public static final String SEARCH_INFRACTOR = "SELECT SIIPTC_PERSONA.NOMBRE, SIIPTC_PERSONA.A_PATERNO, SIIPTC_PERSONA.A_MATERNO, SIIPTC_PERSONA.RFC, SIIPTA_DIRECCION.CALLE, SIIPTA_DIRECCION.EXTERIOR, SIIPTA_DIRECCION.INTERIOR, SIIPTA_DIRECCION.COLONIA, SIIPTC_MUNICIPIO_SEPOMEX.ID_ESTADO, B.ESTADO AS ESTADO_MUNICIPIO, SIIPTC_MUNICIPIO_SEPOMEX.ID_MUNICIPIO, SIIPTC_MUNICIPIO_SEPOMEX.MUNICIPIO, SIIPTA_DIRECCION_PERSONA_INFRACTOR.ID_DIRECCION, SIIPTA_DIRECCION_PERSONA_INFRACTOR.ID_PERSONA, SIIPTA_INFRACCION.NUM_PERMISO_LICENCIA FROM SIIPTA_INFRACCION LEFT JOIN SIIPTA_INFRACCION_PERSONA_INFRACTOR ON SIIPTA_INFRACCION.ID_INFRACCION = SIIPTA_INFRACCION_PERSONA_INFRACTOR.ID_INFRACCION LEFT JOIN SIIPTC_PERSONA ON SIIPTA_INFRACCION_PERSONA_INFRACTOR.ID_PERSONA = SIIPTC_PERSONA.ID_PERSONA LEFT JOIN SIIPTA_DIRECCION_PERSONA_INFRACTOR ON SIIPTC_PERSONA.ID_PERSONA = SIIPTA_DIRECCION_PERSONA_INFRACTOR.ID_PERSONA LEFT JOIN SIIPTA_DIRECCION ON SIIPTA_DIRECCION_PERSONA_INFRACTOR.ID_DIRECCION = SIIPTA_DIRECCION.ID_DIRECCION LEFT JOIN SIIPTC_MUNICIPIO_SEPOMEX ON SIIPTA_DIRECCION.ID_MUNICIPIO = SIIPTC_MUNICIPIO_SEPOMEX.ID_MUNICIPIO LEFT JOIN SIIPTC_ESTADO B ON SIIPTC_MUNICIPIO_SEPOMEX.ID_ESTADO = B.ID_ESTADO LEFT JOIN SIIPTC_ESTADO A ON SIIPTA_INFRACCION.EXPEDIDA_EN_LICENCIA = A.ID_ESTADO LEFT JOIN SIIPTC_INFRACCION_TIPO_LICENCIA ON SIIPTA_INFRACCION.ID_TIPO_LICENCIA = SIIPTC_INFRACCION_TIPO_LICENCIA.ID_TIPO_LICENCIA WHERE SIIPTA_INFRACCION.ID_INFRACCION = '";
                public static final String SEARCH_DISPOSICION = "SELECT SIIPTA_INFRACCION.ID_DISPOSICION, SIIPTC_INFRACCION_DISPOSICION.DISPOSICION FROM SIIPTC_INFRACCION_DISPOSICION LEFT JOIN SIIPTA_INFRACCION ON SIIPTC_INFRACCION_DISPOSICION.ID_DISPOSICION = SIIPTA_INFRACCION.ID_DISPOSICION WHERE SIIPTA_INFRACCION.ID_INFRACCION = '";
                public static final String SEARCH_INFRACTORLIC = "SELECT SIIPTA_INFRACCION.ID_TIPO_LICENCIA, SIIPTC_INFRACCION_TIPO_LICENCIA.TIPO_LICENCIA, SIIPTA_INFRACCION.EXPEDIDA_EN_LICENCIA, SIIPTC_ESTADO.ESTADO FROM SIIPTC_INFRACCION_TIPO_LICENCIA LEFT JOIN SIIPTA_INFRACCION ON SIIPTC_INFRACCION_TIPO_LICENCIA.ID_TIPO_LICENCIA = SIIPTA_INFRACCION.ID_TIPO_LICENCIA LEFT JOIN SIIPTC_ESTADO ON SIIPTA_INFRACCION.EXPEDIDA_EN_LICENCIA = SIIPTC_ESTADO.ID_ESTADO WHERE SIIPTA_INFRACCION.ID_INFRACCION = '";
                public static final String SEARCH_OFICIAL = "SELECT SIIPTC_PERSONA.A_PATERNO|| ' '|| SIIPTC_PERSONA.A_MATERNO|| ' '|| SIIPTC_PERSONA.NOMBRE AS NOMBRE, SIIPTC_PERSONA_AYUNTAMIENTO.EMPLEADO FROM SIIPTC_PERSONA LEFT JOIN SIIPTC_PERSONA_AYUNTAMIENTO ON SIIPTC_PERSONA.ID_PERSONA = SIIPTC_PERSONA_AYUNTAMIENTO.ID_PERSONA WHERE SIIPTC_PERSONA_AYUNTAMIENTO.ID_PERSONA_AYUNTAMIENTO = '";
            }



            public class Update {
                public static final String UPDATE_PERSONA = "UPDATE SIIPTC_PERSONA SET ";
            }
        }
    }

    public class DebugType {
        public static final String DATABASE = "Infracciones DB";
        public static final String VALUES = "Infracciones Values";
        public static final String PRINT = "Infracciones Print";
        public static final String PARSE = "Infracciones Parse";
        public static final String WEB_SERVICE = "Infracciones WS";
        public static final String SERVICE = "Infracciones Service";
        public static final String SYNC = "Infracciones SYNC";
        public static final String INTERNET = "Infracciones CON";
    }

    public class ServiceCode {
        public static final int SPINNER_DATABASE_LOAD = 1;
        public static final int CAMERA_PICTURE = 2;
        public static final int SAVE_COMPLETE = 3;
        public static final int SEARCH_SUCCESS = 4;
        public static final int PRINT = 5;
        public static final int AUTO_SEND_OK = 6;
        public static final int SYNCCATALOGS = 7;
        public static final int SYNCIMAGES = 8;
        public static final int SEARCH_ONLINE_SUCCESS = 9;
        public static final int ONLINITEM = 10;
        public static final int PRINT_TWO = 11;
        public static final int BARCODE_ONE = 12;
        public static final int BARCODE_TWO = 13;

    }

    public class Typedata {
        public static final int CATALOGS = 1;
        public static final int IMAGESYNC = 2;
        public static final int ONLINESEARCH = 3;

        public static final int ONLINEITEM = 4;
    }
}
